### PR TITLE
Added conditional switch between udatetime and datetime for Windows.

### PR DESCRIPTION
**Pull request by Srceh**
Following the gitter discussion, simply added a conditional import "datetime as udatetime" for windows usage, tested with tutorial 1 and 5 on Windows 10 X64.

### CODE REVIEW

**Review by tdiethe — CHANGES_REQUESTED** [review]
Actually looking at it datetime is already imported as well (could check that it's actually used??). In that case it could just be:

+import os
 +if os.name != 'nt':
 +    import udatetime
 +else:
 +    udatetime = datetime

to save an additional import. Could you test this too?

**Comment by Srceh** [comment]
Fixed. Tested with Tutorial 1-5. 

How could I didn't see the import on top.... Should't have programmed on bed before sleep... :(

**Comment by tdiethe** [comment]
Happens to the best of us!

**Comment by tdiethe** [comment]
Do you want to keep the windows branch open?

**Comment by Srceh** [comment]
For current situation I think this branch is no longer needed, hopefully it will run on windows happily...

**Comment by tdiethe** [comment]
Cool!

**Pull request merged**
